
services:
  userapiapp:
    image: userapi
    container_name: userapiapp
    depends_on:
      - postgresdb
    build:
      context: UserWebApi\Dockerfile
      dockerfile: Dockerfile
    expose:
      - 8082
    ports:
      - 8082:8080
    networks:
      - librarynetwork
    restart: always

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=Secret12345!
      - POSTGRES_DB=userdatabase
    expose:
      - 5342
    ports:
      - 5342:5342
    networks:
      - librarynetwork
    volumes:
      - userpostgresvolume:/data/db
      - userpostgresvolume:/data/configdb
    restart: always

  bookapiapp:
    image: bookapi
    container_name: bookapiapp
    depends_on:
      - mongodb
    build:
      context: BookWebApi\Dockerfile
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - 8081:8080
    networks:
      - librarynetwork
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - librarynetwork
    volumes:
      - librarymongovolume:/data/db
      - librarymongovolume:/data/configdb
    restart: always  

networks:
  librarynetwork:
    driver: bridge

volumes:
  librarymongovolume:
  userpostgresvolume: